all_joints:
- - 0
- - 1
all_joints_names:
- snout
- tail
batch_size: 8
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_PE5Oct20/PE5_HM95shuffle1.pickle
dataset_type: multi-animal-imgaug
display_iters: 500
global_scale: 0.8
init_weights: /home/grads/l/larcwind/Desktop/Codes/DeepLabCut-master/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_PE5Oct20/Documentation_data-PE5_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: resnet_50
num_joints: 2
num_limbs: 1
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
partaffinityfield_predict: true
pos_dist_thresh: 17
project_path: /home/grads/l/larcwind/Desktop/Codes/DeepLabCut-master/PE5-HM-2020-10-20
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
weigh_only_present_joints: false
